// auto-generated: pexels-curated dataset for ywee
export const DATA = {
  "brand": {
    "name": "ywee",
    "tagline": "Considered Clothing",
    "since": "Lisbon, est. 2018"
  },
  "hero": {
    "video": {
      "id": 8151972,
      "duration": 9,
      "width": 1080,
      "height": 1920,
      "url": "https://www.pexels.com/video/a-man-walking-on-street-8151972/",
      "user": "RDNE Stock project",
      "src": "https://videos.pexels.com/video-files/8151972/8151972-hd_1080_1920_30fps.mp4",
      "poster": "https://images.pexels.com/videos/8151972/pictures/preview-0.jpeg"
    },
    "portraits": [
      {
        "id": 31844257,
        "color": "#465955",
        "url": "https://www.pexels.com/photo/futuristic-fashion-portrait-in-minimal-light-31844257/",
        "photographer": "Omotayo Samuel",
        "alt": "Elegant portrait of a model in futuristic attire against a dark backdrop.",
        "src": "https://images.pexels.com/photos/31844257/pexels-photo-31844257.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/31844257/pexels-photo-31844257.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/31844257/pexels-photo-31844257.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/31844257/pexels-photo-31844257.jpeg",
        "src_tiny": "https://images.pexels.com/photos/31844257/pexels-photo-31844257.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4480,
        "height": 6720
      },
      {
        "id": 20520684,
        "color": "#737373",
        "url": "https://www.pexels.com/photo/studio-shot-of-woman-kneeling-in-coat-20520684/",
        "photographer": "Alina Matveycheva",
        "alt": "Stylish black and white studio portrait of woman in coat with floral accessory kneeling gracefully.",
        "src": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg",
        "src_tiny": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4009,
        "height": 6013
      },
      {
        "id": 8441407,
        "color": "#A4A4AC",
        "url": "https://www.pexels.com/photo/a-model-in-leather-outfit-stretching-legs-8441407/",
        "photographer": "cottonbro studio",
        "alt": "Conceptual studio shot of a model posing in black leather outfit with numbers projected in background.",
        "src": "https://images.pexels.com/photos/8441407/pexels-photo-8441407.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/8441407/pexels-photo-8441407.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/8441407/pexels-photo-8441407.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/8441407/pexels-photo-8441407.jpeg",
        "src_tiny": "https://images.pexels.com/photos/8441407/pexels-photo-8441407.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4440,
        "height": 6660
      },
      {
        "id": 10211651,
        "color": "#BFBEB9",
        "url": "https://www.pexels.com/photo/a-woman-in-white-clothes-leaning-on-the-white-wall-10211651/",
        "photographer": "cottonbro studio",
        "alt": "Artistic studio portrait of two women dressed in white, showcasing minimalism and elegance.",
        "src": "https://images.pexels.com/photos/10211651/pexels-photo-10211651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/10211651/pexels-photo-10211651.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/10211651/pexels-photo-10211651.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/10211651/pexels-photo-10211651.jpeg",
        "src_tiny": "https://images.pexels.com/photos/10211651/pexels-photo-10211651.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 5304,
        "height": 7952
      },
      {
        "id": 8441421,
        "color": "#A8A9AE",
        "url": "https://www.pexels.com/photo/a-woman-in-black-clothes-near-a-white-wall-8441421/",
        "photographer": "cottonbro studio",
        "alt": "Stylish woman in black leather and pleated skirt posing against a white wall with shadow play.",
        "src": "https://images.pexels.com/photos/8441421/pexels-photo-8441421.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/8441421/pexels-photo-8441421.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/8441421/pexels-photo-8441421.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/8441421/pexels-photo-8441421.jpeg",
        "src_tiny": "https://images.pexels.com/photos/8441421/pexels-photo-8441421.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4062,
        "height": 6093
      },
      {
        "id": 36624450,
        "color": "#A8A8A8",
        "url": "https://www.pexels.com/photo/stylish-monochrome-fashion-portrait-from-behind-36624450/",
        "photographer": "Alina Zhabynska",
        "alt": "A black and white photo of a person in a trench coat viewed from behind.",
        "src": "https://images.pexels.com/photos/36624450/pexels-photo-36624450.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/36624450/pexels-photo-36624450.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/36624450/pexels-photo-36624450.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/36624450/pexels-photo-36624450.jpeg",
        "src_tiny": "https://images.pexels.com/photos/36624450/pexels-photo-36624450.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 5152,
        "height": 7728
      },
      {
        "id": 20847726,
        "color": "#939393",
        "url": "https://www.pexels.com/photo/black-and-white-photography-of-a-woman-posing-in-a-studio-20847726/",
        "photographer": "Alina Matveycheva",
        "alt": "Elegant woman in black dress and boots posing for a studio portrait.",
        "src": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg",
        "src_tiny": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4157,
        "height": 6236
      },
      {
        "id": 11594664,
        "color": "#BDBDBD",
        "url": "https://www.pexels.com/photo/fashion-model-posing-barefoot-11594664/",
        "photographer": "\u0415\u043a\u0430\u0442\u0435\u0440\u0438\u043d\u0430 \u041b\u0435\u0431\u0435\u0434\u044c",
        "alt": "Elegant woman posing in black and white studio photo, showcasing fashion style.",
        "src": "https://images.pexels.com/photos/11594664/pexels-photo-11594664.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "src_portrait": "https://images.pexels.com/photos/11594664/pexels-photo-11594664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
        "src_landscape": "https://images.pexels.com/photos/11594664/pexels-photo-11594664.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        "src_original": "https://images.pexels.com/photos/11594664/pexels-photo-11594664.jpeg",
        "src_tiny": "https://images.pexels.com/photos/11594664/pexels-photo-11594664.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
        "width": 4000,
        "height": 6000
      }
    ]
  },
  "products": [
    {
      "id": 11447057,
      "sku": "YW47057",
      "slug": "verre-wool-coat-11447057",
      "name": "Verre Wool Coat",
      "category": "Outerwear",
      "price": 900,
      "currency": "USD",
      "color": "Bone",
      "color_hex": "#9F9999",
      "alt": "Young woman in a warm wool coat posing outdoors during winter.",
      "img": "https://images.pexels.com/photos/11447057/pexels-photo-11447057.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/11447057/pexels-photo-11447057.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/11447057/pexels-photo-11447057.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/11447057/pexels-photo-11447057.jpeg",
      "img_tiny": "https://images.pexels.com/photos/11447057/pexels-photo-11447057.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Ilya Komov",
      "url_pexels": "https://www.pexels.com/photo/a-woman-wearing-a-wool-coat-11447057/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Heritage trench reissued in storm-cotton gabardine with hand-finished bartacks and a removable wool liner. Considered for daily commute.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 31153342,
      "sku": "YW53342",
      "slug": "halden-trench-31153342",
      "name": "Halden Trench",
      "category": "Outerwear",
      "price": 580,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#9E9996",
      "alt": "Woman in beige coat and boots posing in snowy field with chair.",
      "img": "https://images.pexels.com/photos/31153342/pexels-photo-31153342.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/31153342/pexels-photo-31153342.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/31153342/pexels-photo-31153342.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/31153342/pexels-photo-31153342.jpeg",
      "img_tiny": "https://images.pexels.com/photos/31153342/pexels-photo-31153342.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "iddea photo",
      "url_pexels": "https://www.pexels.com/photo/stylish-woman-in-winter-coat-by-chair-outdoors-31153342/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "A long-line overcoat in undyed virgin wool. Single-vent back, bemberg lining, and pure horn buttons. Made to age in.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 12989422,
      "sku": "YW89422",
      "slug": "nera-overcoat-12989422",
      "name": "Nera Overcoat",
      "category": "Outerwear",
      "price": 940,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#7E6D64",
      "alt": "Chic woman standing indoors wearing a fashionable brown wool coat, embodying modern winter style.",
      "img": "https://images.pexels.com/photos/12989422/pexels-photo-12989422.png?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/12989422/pexels-photo-12989422.png?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/12989422/pexels-photo-12989422.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/12989422/pexels-photo-12989422.png",
      "img_tiny": "https://images.pexels.com/photos/12989422/pexels-photo-12989422.png?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Misho chachanidze",
      "url_pexels": "https://www.pexels.com/photo/beautiful-woman-wearing-coat-12989422/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Cut from regenerated Italian wool with a relaxed shoulder, dropped sleeves, and a tonal horn button placket. Tailored in Northern Portugal.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 11447037,
      "sku": "YW47037",
      "slug": "maru-topcoat-11447037",
      "name": "Maru Topcoat",
      "category": "Outerwear",
      "price": 520,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#AFADAE",
      "alt": "Warm winter portrait of a woman standing outdoors in a wool coat.",
      "img": "https://images.pexels.com/photos/11447037/pexels-photo-11447037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/11447037/pexels-photo-11447037.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/11447037/pexels-photo-11447037.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/11447037/pexels-photo-11447037.jpeg",
      "img_tiny": "https://images.pexels.com/photos/11447037/pexels-photo-11447037.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Ilya Komov",
      "url_pexels": "https://www.pexels.com/photo/portrait-of-a-woman-in-winter-11447037/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Heritage trench reissued in storm-cotton gabardine with hand-finished bartacks and a removable wool liner. Considered for daily commute.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 5119919,
      "sku": "YW19919",
      "slug": "solene-peacoat-5119919",
      "name": "Solene Peacoat",
      "category": "Outerwear",
      "price": 550,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#766A5B",
      "alt": "Stylish group wearing trench coats in an outdoor desert setting, showcasing modern fashion.",
      "img": "https://images.pexels.com/photos/5119919/pexels-photo-5119919.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/5119919/pexels-photo-5119919.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/5119919/pexels-photo-5119919.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/5119919/pexels-photo-5119919.jpeg",
      "img_tiny": "https://images.pexels.com/photos/5119919/pexels-photo-5119919.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "cottonbro studio",
      "url_pexels": "https://www.pexels.com/photo/a-man-in-beige-trench-coat-and-black-shirt-5119919/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "A long-line overcoat in undyed virgin wool. Single-vent back, bemberg lining, and pure horn buttons. Made to age in.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 14642651,
      "sku": "YW42651",
      "slug": "maon-cashmere-knit-14642651",
      "name": "Maon Cashmere Knit",
      "category": "Knitwear",
      "price": 270,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#736258",
      "alt": "Warm knitted sweaters in beige and cream hues, ideal for comfy winter fashion.",
      "img": "https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg",
      "img_tiny": "https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Nati",
      "url_pexels": "https://www.pexels.com/photo/a-close-up-shot-of-a-knitted-clothing-14642651/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Six-ply merino with a high-twist yarn for shape retention. Mock neck, raglan shoulder, ribbed cuff. Dyed in small batches.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 5789010,
      "sku": "YW89010",
      "slug": "briar-roll-neck-5789010",
      "name": "Briar Roll Neck",
      "category": "Knitwear",
      "price": 380,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#B2A69B",
      "alt": "Elegant woman in a knitted sweater holding a woven bag. Perfect for fashion and lifestyle concepts.",
      "img": "https://images.pexels.com/photos/5789010/pexels-photo-5789010.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/5789010/pexels-photo-5789010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/5789010/pexels-photo-5789010.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/5789010/pexels-photo-5789010.jpeg",
      "img_tiny": "https://images.pexels.com/photos/5789010/pexels-photo-5789010.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Pavel Danilyuk",
      "url_pexels": "https://www.pexels.com/photo/a-woman-in-brown-knitted-sweater-holding-a-basket-5789010/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Compact-knit wool with hand-linked seams. Designed to layer beneath outerwear or stand alone with tailored trousers.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 13889763,
      "sku": "YW89763",
      "slug": "linde-crew-13889763",
      "name": "Linde Crew",
      "category": "Knitwear",
      "price": 240,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#8E8983",
      "alt": "A vertical stack of cozy knitted sweaters in neutral tones offers warmth and texture.",
      "img": "https://images.pexels.com/photos/13889763/pexels-photo-13889763.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/13889763/pexels-photo-13889763.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/13889763/pexels-photo-13889763.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/13889763/pexels-photo-13889763.jpeg",
      "img_tiny": "https://images.pexels.com/photos/13889763/pexels-photo-13889763.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "B\u00fc\u015fra \u0130nce",
      "url_pexels": "https://www.pexels.com/photo/stack-of-sweaters-13889763/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Spun in our Inner Mongolia mill from grade-A cashmere. Boxy fit with a slow-finished hem. Soft, structural, breathable.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 14641437,
      "sku": "YW41437",
      "slug": "sten-cable-knit-14641437",
      "name": "Sten Cable Knit",
      "category": "Knitwear",
      "price": 330,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#8E8683",
      "alt": "A neatly stacked pile of cozy knitted sweaters in neutral tones on a bed.",
      "img": "https://images.pexels.com/photos/14641437/pexels-photo-14641437.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/14641437/pexels-photo-14641437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/14641437/pexels-photo-14641437.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/14641437/pexels-photo-14641437.jpeg",
      "img_tiny": "https://images.pexels.com/photos/14641437/pexels-photo-14641437.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Nati",
      "url_pexels": "https://www.pexels.com/photo/sweaters-stacked-on-bedclothes-14641437/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Six-ply merino with a high-twist yarn for shape retention. Mock neck, raglan shoulder, ribbed cuff. Dyed in small batches.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 19203177,
      "sku": "YW03177",
      "slug": "iris-mohair-sweater-19203177",
      "name": "Iris Mohair Sweater",
      "category": "Knitwear",
      "price": 240,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#96B5C7",
      "alt": "Detailed close-up of blue knitted fabric showing its texture and pattern, perfect for textile and design projects.",
      "img": "https://images.pexels.com/photos/19203177/pexels-photo-19203177.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/19203177/pexels-photo-19203177.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/19203177/pexels-photo-19203177.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/19203177/pexels-photo-19203177.jpeg",
      "img_tiny": "https://images.pexels.com/photos/19203177/pexels-photo-19203177.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Diana \u2728",
      "url_pexels": "https://www.pexels.com/photo/texture-of-cotton-sweater-19203177/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Compact-knit wool with hand-linked seams. Designed to layer beneath outerwear or stand alone with tailored trousers.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 18031037,
      "sku": "YW31037",
      "slug": "otae-linen-shirt-18031037",
      "name": "Otae Linen Shirt",
      "category": "Tops",
      "price": 190,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#797470",
      "alt": "A low-angle portrait of a man in a fashionable linen suit amidst lush greenery.",
      "img": "https://images.pexels.com/photos/18031037/pexels-photo-18031037.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/18031037/pexels-photo-18031037.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/18031037/pexels-photo-18031037.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/18031037/pexels-photo-18031037.jpeg",
      "img_tiny": "https://images.pexels.com/photos/18031037/pexels-photo-18031037.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Elif",
      "url_pexels": "https://www.pexels.com/photo/man-in-linen-suit-18031037/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Lightweight cotton poplin, single-needle stitching, French seams. A workshop staple for warmer rooms.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 5149729,
      "sku": "YW49729",
      "slug": "plage-poplin-blouse-5149729",
      "name": "Plage Poplin Blouse",
      "category": "Tops",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#5F746D",
      "alt": "Side view of adult brave male in light clothing in front of white curtain looking away",
      "img": "https://images.pexels.com/photos/5149729/pexels-photo-5149729.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/5149729/pexels-photo-5149729.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/5149729/pexels-photo-5149729.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/5149729/pexels-photo-5149729.jpeg",
      "img_tiny": "https://images.pexels.com/photos/5149729/pexels-photo-5149729.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "emre keshavarz",
      "url_pexels": "https://www.pexels.com/photo/trendy-brutal-man-with-modern-hairstyle-squinting-5149729/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Sandwashed silk crepe with a bias-cut yoke and rolled hems. Made to feel weightless under a coat.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 5191435,
      "sku": "YW91435",
      "slug": "riva-silk-top-5191435",
      "name": "Riva Silk Top",
      "category": "Tops",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#848484",
      "alt": "Black and white of busy pensive male buttoning shirt in sunny clear weather",
      "img": "https://images.pexels.com/photos/5191435/pexels-photo-5191435.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/5191435/pexels-photo-5191435.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/5191435/pexels-photo-5191435.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/5191435/pexels-photo-5191435.jpeg",
      "img_tiny": "https://images.pexels.com/photos/5191435/pexels-photo-5191435.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "emre keshavarz",
      "url_pexels": "https://www.pexels.com/photo/slim-man-with-curly-hair-fastening-shirt-5191435/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Garment-washed Belgian linen with a softened collar and shell buttons. Designed to drape, not to crease.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 18031216,
      "sku": "YW31216",
      "slug": "asphalt-camp-shirt-18031216",
      "name": "Asphalt Camp Shirt",
      "category": "Tops",
      "price": 190,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#42474B",
      "alt": "A fashionable man in a floral shirt and linen suit sits outdoors with a relaxed expression, combining elegance with a casual urban vibe.",
      "img": "https://images.pexels.com/photos/18031216/pexels-photo-18031216.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/18031216/pexels-photo-18031216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/18031216/pexels-photo-18031216.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/18031216/pexels-photo-18031216.jpeg",
      "img_tiny": "https://images.pexels.com/photos/18031216/pexels-photo-18031216.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Elif",
      "url_pexels": "https://www.pexels.com/photo/elegant-man-sitting-in-floral-shirt-and-linen-suit-18031216/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Lightweight cotton poplin, single-needle stitching, French seams. A workshop staple for warmer rooms.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 14196299,
      "sku": "YW96299",
      "slug": "maeve-oxford-14196299",
      "name": "Maeve Oxford",
      "category": "Tops",
      "price": 250,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#7D675C",
      "alt": "Elegant brunette woman posing in white blouse indoors.",
      "img": "https://images.pexels.com/photos/14196299/pexels-photo-14196299.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/14196299/pexels-photo-14196299.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/14196299/pexels-photo-14196299.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/14196299/pexels-photo-14196299.jpeg",
      "img_tiny": "https://images.pexels.com/photos/14196299/pexels-photo-14196299.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "rehman yousaf",
      "url_pexels": "https://www.pexels.com/photo/portrait-of-a-woman-looking-down-14196299/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L",
        "XL"
      ],
      "description": "Sandwashed silk crepe with a bias-cut yoke and rolled hems. Made to feel weightless under a coat.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 8276604,
      "sku": "YW76604",
      "slug": "mille-wide-trouser-8276604",
      "name": "Mille Wide Trouser",
      "category": "Bottoms",
      "price": 250,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#686657",
      "alt": "Two fashionable men walking confidently in a city park, showcasing modern styles.",
      "img": "https://images.pexels.com/photos/8276604/pexels-photo-8276604.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/8276604/pexels-photo-8276604.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/8276604/pexels-photo-8276604.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/8276604/pexels-photo-8276604.jpeg",
      "img_tiny": "https://images.pexels.com/photos/8276604/pexels-photo-8276604.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "PNW Production",
      "url_pexels": "https://www.pexels.com/photo/businessmen-walking-together-8276604/",
      "sizes": [
        "26",
        "28",
        "30",
        "32",
        "34",
        "36"
      ],
      "description": "Selvedge denim woven on shuttle looms in Okayama. Mid-rise, straight leg, raw indigo that fades with you.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 9634508,
      "sku": "YW34508",
      "slug": "lanai-pleated-pant-9634508",
      "name": "Lanai Pleated Pant",
      "category": "Bottoms",
      "price": 400,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#AC9085",
      "alt": "Two women sitting and showcasing stylish modern suits indoors.",
      "img": "https://images.pexels.com/photos/9634508/pexels-photo-9634508.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/9634508/pexels-photo-9634508.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/9634508/pexels-photo-9634508.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/9634508/pexels-photo-9634508.jpeg",
      "img_tiny": "https://images.pexels.com/photos/9634508/pexels-photo-9634508.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "cottonbro studio",
      "url_pexels": "https://www.pexels.com/photo/person-wearing-orange-blazer-and-pants-9634508/",
      "sizes": [
        "26",
        "28",
        "30",
        "32",
        "34",
        "36"
      ],
      "description": "Italian cotton drill with a tucked waistband and slanted side seams. Tailored relaxed for daily wear.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 33571184,
      "sku": "YW71184",
      "slug": "atlas-tailored-slack-33571184",
      "name": "Atlas Tailored Slack",
      "category": "Bottoms",
      "price": 220,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#514E47",
      "alt": "Elegant man in business attire posing confidently on a step, outdoors.",
      "img": "https://images.pexels.com/photos/33571184/pexels-photo-33571184.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/33571184/pexels-photo-33571184.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/33571184/pexels-photo-33571184.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/33571184/pexels-photo-33571184.jpeg",
      "img_tiny": "https://images.pexels.com/photos/33571184/pexels-photo-33571184.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Plus Minus",
      "url_pexels": "https://www.pexels.com/photo/stylish-man-posing-in-modern-business-attire-33571184/",
      "sizes": [
        "26",
        "28",
        "30",
        "32",
        "34",
        "36"
      ],
      "description": "High-rise wool gabardine with double pleats and a deep cuff. Cut for a relaxed leg and a clean break at the shoe.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 34319008,
      "sku": "YW19008",
      "slug": "ruse-selvedge-jean-34319008",
      "name": "Ruse Selvedge Jean",
      "category": "Bottoms",
      "price": 250,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#242623",
      "alt": "Close-up of a man adjusting a gray suit jacket outdoors, focusing on style and professionalism.",
      "img": "https://images.pexels.com/photos/34319008/pexels-photo-34319008.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/34319008/pexels-photo-34319008.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/34319008/pexels-photo-34319008.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/34319008/pexels-photo-34319008.jpeg",
      "img_tiny": "https://images.pexels.com/photos/34319008/pexels-photo-34319008.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Alexander Mass",
      "url_pexels": "https://www.pexels.com/photo/man-fastening-suit-jacket-outdoors-34319008/",
      "sizes": [
        "26",
        "28",
        "30",
        "32",
        "34",
        "36"
      ],
      "description": "Selvedge denim woven on shuttle looms in Okayama. Mid-rise, straight leg, raw indigo that fades with you.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 26011862,
      "sku": "YW11862",
      "slug": "holm-carpenter-26011862",
      "name": "Holm Carpenter",
      "category": "Bottoms",
      "price": 310,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#444645",
      "alt": "A fashionable woman in denim jacket and jeans poses in a studio with a black background.",
      "img": "https://images.pexels.com/photos/26011862/pexels-photo-26011862.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/26011862/pexels-photo-26011862.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/26011862/pexels-photo-26011862.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/26011862/pexels-photo-26011862.jpeg",
      "img_tiny": "https://images.pexels.com/photos/26011862/pexels-photo-26011862.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Alina Matveycheva",
      "url_pexels": "https://www.pexels.com/photo/woman-standing-in-jean-jacket-and-leaning-on-chair-26011862/",
      "sizes": [
        "26",
        "28",
        "30",
        "32",
        "34",
        "36"
      ],
      "description": "Italian cotton drill with a tucked waistband and slanted side seams. Tailored relaxed for daily wear.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 8441561,
      "sku": "YW41561",
      "slug": "solene-slip-dress-8441561",
      "name": "Sol\u00e8ne Slip Dress",
      "category": "Dresses",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#A1A1A3",
      "alt": "A conceptual portrait of two models in avant-garde fashion against a minimalist background.",
      "img": "https://images.pexels.com/photos/8441561/pexels-photo-8441561.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/8441561/pexels-photo-8441561.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/8441561/pexels-photo-8441561.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/8441561/pexels-photo-8441561.jpeg",
      "img_tiny": "https://images.pexels.com/photos/8441561/pexels-photo-8441561.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "cottonbro studio",
      "url_pexels": "https://www.pexels.com/photo/a-man-in-black-leather-coat-standing-in-front-of-a-woman-wearing-white-dress-8441561/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L"
      ],
      "description": "Mid-weight viscose crepe with a hand-finished tie waist and softly pleated sleeve. Cut for movement.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 20520684,
      "sku": "YW20684",
      "slug": "brume-wrap-dress-20520684",
      "name": "Brume Wrap Dress",
      "category": "Dresses",
      "price": 500,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#737373",
      "alt": "Stylish black and white studio portrait of woman in coat with floral accessory kneeling gracefully.",
      "img": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg",
      "img_tiny": "https://images.pexels.com/photos/20520684/pexels-photo-20520684.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Alina Matveycheva",
      "url_pexels": "https://www.pexels.com/photo/studio-shot-of-woman-kneeling-in-coat-20520684/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L"
      ],
      "description": "Stretch wool sheath with a reinforced zip placket. A workroom dress designed to travel.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 2345236,
      "sku": "YW45236",
      "slug": "mira-sheath-2345236",
      "name": "Mira Sheath",
      "category": "Dresses",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#4F4F4F",
      "alt": "Elegant model posing in a monochrome editorial fashion shoot outdoors.",
      "img": "https://images.pexels.com/photos/2345236/pexels-photo-2345236.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/2345236/pexels-photo-2345236.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/2345236/pexels-photo-2345236.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/2345236/pexels-photo-2345236.jpeg",
      "img_tiny": "https://images.pexels.com/photos/2345236/pexels-photo-2345236.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Two Dreamers",
      "url_pexels": "https://www.pexels.com/photo/woman-wearing-couture-dress-2345236/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L"
      ],
      "description": "Bias-cut sandwashed silk with French seams. Adjustable spaghetti straps and a mother-of-pearl hook closure.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 20847726,
      "sku": "YW47726",
      "slug": "halia-column-20847726",
      "name": "Halia Column",
      "category": "Dresses",
      "price": 370,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#939393",
      "alt": "Elegant woman in black dress and boots posing for a studio portrait.",
      "img": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg",
      "img_tiny": "https://images.pexels.com/photos/20847726/pexels-photo-20847726.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Alina Matveycheva",
      "url_pexels": "https://www.pexels.com/photo/black-and-white-photography-of-a-woman-posing-in-a-studio-20847726/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L"
      ],
      "description": "Mid-weight viscose crepe with a hand-finished tie waist and softly pleated sleeve. Cut for movement.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 34891485,
      "sku": "YW91485",
      "slug": "pell-tailored-dress-34891485",
      "name": "Pell Tailored Dress",
      "category": "Dresses",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#655E58",
      "alt": "Woman in pink dress lounging in vintage chair, natural light indoors.",
      "img": "https://images.pexels.com/photos/34891485/pexels-photo-34891485.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/34891485/pexels-photo-34891485.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/34891485/pexels-photo-34891485.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/34891485/pexels-photo-34891485.jpeg",
      "img_tiny": "https://images.pexels.com/photos/34891485/pexels-photo-34891485.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Guillermo Berlin",
      "url_pexels": "https://www.pexels.com/photo/elegant-woman-in-vintage-armchair-by-window-34891485/",
      "sizes": [
        "XS",
        "S",
        "M",
        "L"
      ],
      "description": "Stretch wool sheath with a reinforced zip placket. A workroom dress designed to travel.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 34683579,
      "sku": "YW83579",
      "slug": "rune-leather-tote-34683579",
      "name": "Rune Leather Tote",
      "category": "Accessories",
      "price": 200,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#888380",
      "alt": "Brown leather shoulder bag with flowers hanging on a city street, blending fashion with nature.",
      "img": "https://images.pexels.com/photos/34683579/pexels-photo-34683579.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/34683579/pexels-photo-34683579.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/34683579/pexels-photo-34683579.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/34683579/pexels-photo-34683579.jpeg",
      "img_tiny": "https://images.pexels.com/photos/34683579/pexels-photo-34683579.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Ravi Kant",
      "url_pexels": "https://www.pexels.com/photo/stylish-leather-bag-with-flowers-on-urban-street-34683579/",
      "sizes": [
        "One Size"
      ],
      "description": "Whole-cut calf with a leather sole and Goodyear welt. Made by hand in Igualada, Spain.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 33223468,
      "sku": "YW23468",
      "slug": "halden-card-holder-33223468",
      "name": "Halden Card Holder",
      "category": "Accessories",
      "price": 280,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#5D3722",
      "alt": "A collection of vintage leather bags in various styles and colors showcased in a market stall.",
      "img": "https://images.pexels.com/photos/33223468/pexels-photo-33223468.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/33223468/pexels-photo-33223468.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/33223468/pexels-photo-33223468.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/33223468/pexels-photo-33223468.jpeg",
      "img_tiny": "https://images.pexels.com/photos/33223468/pexels-photo-33223468.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Hakim LEVEL",
      "url_pexels": "https://www.pexels.com/photo/vintage-leather-bags-display-in-market-stall-33223468/",
      "sizes": [
        "One Size"
      ],
      "description": "Heritage horween leather, hand-stitched seams, and a discreet brass tab. A piece designed to outlast a decade.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 36492563,
      "sku": "YW92563",
      "slug": "pris-calf-boot-36492563",
      "name": "Pris Calf Boot",
      "category": "Accessories",
      "price": 680,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#856968",
      "alt": "A detailed view of a brown leather messenger bag with brass accents.",
      "img": "https://images.pexels.com/photos/36492563/pexels-photo-36492563.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/36492563/pexels-photo-36492563.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/36492563/pexels-photo-36492563.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/36492563/pexels-photo-36492563.jpeg",
      "img_tiny": "https://images.pexels.com/photos/36492563/pexels-photo-36492563.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Ya\u015far Ba\u015fkurt",
      "url_pexels": "https://www.pexels.com/photo/close-up-of-stylish-leather-messenger-bag-36492563/",
      "sizes": [
        "One Size"
      ],
      "description": "Vegetable-tanned Tuscan leather. Hand-burnished edges, brass fittings, and a custom debossed mark on the inner spine.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 26316173,
      "sku": "YW16173",
      "slug": "bren-driving-loafer-26316173",
      "name": "Bren Driving Loafer",
      "category": "Accessories",
      "price": 200,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#9F8D7F",
      "alt": "Close-up of a fashionably dressed woman holding a leather tote bag with a newspaper.",
      "img": "https://images.pexels.com/photos/26316173/pexels-photo-26316173.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/26316173/pexels-photo-26316173.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/26316173/pexels-photo-26316173.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/26316173/pexels-photo-26316173.jpeg",
      "img_tiny": "https://images.pexels.com/photos/26316173/pexels-photo-26316173.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "G\u00fcl I\u015f\u0131k",
      "url_pexels": "https://www.pexels.com/photo/woman-holding-bag-26316173/",
      "sizes": [
        "One Size"
      ],
      "description": "Whole-cut calf with a leather sole and Goodyear welt. Made by hand in Igualada, Spain.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    },
    {
      "id": 33937416,
      "sku": "YW37416",
      "slug": "asher-belt-33937416",
      "name": "Asher Belt",
      "category": "Accessories",
      "price": 170,
      "currency": "USD",
      "color": "Natural",
      "color_hex": "#2D3027",
      "alt": "Stylish black leather combat boots on blurred background, ideal for fashion and outdoor themes.",
      "img": "https://images.pexels.com/photos/33937416/pexels-photo-33937416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "img_portrait": "https://images.pexels.com/photos/33937416/pexels-photo-33937416.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "img_landscape": "https://images.pexels.com/photos/33937416/pexels-photo-33937416.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "img_original": "https://images.pexels.com/photos/33937416/pexels-photo-33937416.jpeg",
      "img_tiny": "https://images.pexels.com/photos/33937416/pexels-photo-33937416.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "photographer": "Jonathan Cooper",
      "url_pexels": "https://www.pexels.com/photo/close-up-of-black-leather-combat-boots-outdoors-33937416/",
      "sizes": [
        "One Size"
      ],
      "description": "Heritage horween leather, hand-stitched seams, and a discreet brass tab. A piece designed to outlast a decade.",
      "details": [
        "Made in small batches by independent workshops",
        "Considered cut, hand-finished seams",
        "Natural fibres \u2014 biodegradable at end of life",
        "Free worldwide shipping over $250",
        "Lifetime mending program"
      ],
      "story": "Designed in our Lisbon studio. Cut and finished by hand in family-run ateliers across Portugal, Spain, and northern Italy. We source materials from mills that hold OEKO-TEX or GOTS certifications."
    }
  ],
  "collections": [
    {
      "name": "Atelier",
      "tagline": "Cut and considered. Pieces for the workroom, the gallery, the long lunch.",
      "count": 24,
      "season": "Resort 26",
      "img": "https://images.pexels.com/photos/31167801/pexels-photo-31167801.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "color": "#65060C"
    },
    {
      "name": "Daywear",
      "tagline": "A small wardrobe of essentials, made in mills we visit ourselves.",
      "count": 38,
      "season": "Spring 26",
      "img": "https://images.pexels.com/photos/7671168/pexels-photo-7671168.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "color": "#83827D"
    },
    {
      "name": "Studio",
      "tagline": "Investigations and experiments. Limited cuts, numbered, never re-issued.",
      "count": 12,
      "season": "Edition 04",
      "img": "https://images.pexels.com/photos/9849657/pexels-photo-9849657.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "color": "#6C5245"
    }
  ],
  "lookbook": [
    {
      "id": 1343522,
      "color": "#5B454B",
      "url": "https://www.pexels.com/photo/woman-standing-on-stage-with-hands-on-waist-1343522/",
      "photographer": "Genaro Serv\u00edn",
      "alt": "Dynamic fashion model on stage at a vibrant Morelia fashion show.",
      "src": "https://images.pexels.com/photos/1343522/pexels-photo-1343522.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/1343522/pexels-photo-1343522.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/1343522/pexels-photo-1343522.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/1343522/pexels-photo-1343522.jpeg",
      "src_tiny": "https://images.pexels.com/photos/1343522/pexels-photo-1343522.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6016,
      "height": 4000
    },
    {
      "id": 5185596,
      "color": "#5C545E",
      "url": "https://www.pexels.com/photo/a-model-in-a-fashion-show-5185596/",
      "photographer": "Yogendra  Singh",
      "alt": "Elegant model in lavender gown showcases high fashion on runway during Indian fashion week event.",
      "src": "https://images.pexels.com/photos/5185596/pexels-photo-5185596.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/5185596/pexels-photo-5185596.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/5185596/pexels-photo-5185596.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/5185596/pexels-photo-5185596.jpeg",
      "src_tiny": "https://images.pexels.com/photos/5185596/pexels-photo-5185596.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6000,
      "height": 4000
    },
    {
      "id": 1343524,
      "color": "#38394A",
      "url": "https://www.pexels.com/photo/women-s-white-v-neck-spaghetti-strap-top-and-blue-skirt-1343524/",
      "photographer": "Genaro Serv\u00edn",
      "alt": "Fashion model strutting on a runway during a glamorous evening event with vibrant lights in Morelia, Mexico.",
      "src": "https://images.pexels.com/photos/1343524/pexels-photo-1343524.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/1343524/pexels-photo-1343524.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/1343524/pexels-photo-1343524.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/1343524/pexels-photo-1343524.jpeg",
      "src_tiny": "https://images.pexels.com/photos/1343524/pexels-photo-1343524.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6016,
      "height": 4000
    },
    {
      "id": 5185594,
      "color": "#554B63",
      "url": "https://www.pexels.com/photo/a-model-in-a-white-dress-on-a-catwalk-5185594/",
      "photographer": "Yogendra  Singh",
      "alt": "Model walking the runway in a stunning white dress at a fashion show.",
      "src": "https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg",
      "src_tiny": "https://images.pexels.com/photos/5185594/pexels-photo-5185594.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6000,
      "height": 4000
    },
    {
      "id": 8221274,
      "color": "#9C7D6B",
      "url": "https://www.pexels.com/photo/woman-in-a-pink-coat-standing-on-a-rough-terrain-8221274/",
      "photographer": "Mikhail Nilov",
      "alt": "A model in a pink coat poses in a vibrant desert landscape with a silver ball, blending fashion and futurism.",
      "src": "https://images.pexels.com/photos/8221274/pexels-photo-8221274.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/8221274/pexels-photo-8221274.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/8221274/pexels-photo-8221274.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/8221274/pexels-photo-8221274.jpeg",
      "src_tiny": "https://images.pexels.com/photos/8221274/pexels-photo-8221274.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 7952,
      "height": 5304
    },
    {
      "id": 8221405,
      "color": "#725847",
      "url": "https://www.pexels.com/photo/women-in-trendy-outfits-posing-on-a-rock-8221405/",
      "photographer": "Mikhail Nilov",
      "alt": "Fashion models in trendy outfits posing on rocky terrain under clear skies.",
      "src": "https://images.pexels.com/photos/8221405/pexels-photo-8221405.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/8221405/pexels-photo-8221405.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/8221405/pexels-photo-8221405.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/8221405/pexels-photo-8221405.jpeg",
      "src_tiny": "https://images.pexels.com/photos/8221405/pexels-photo-8221405.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 7952,
      "height": 5304
    },
    {
      "id": 8221363,
      "color": "#75503D",
      "url": "https://www.pexels.com/photo/women-in-transparent-raincoats-walking-while-holding-hands-8221363/",
      "photographer": "Mikhail Nilov",
      "alt": "Two women in transparent raincoats walk across a striking desert landscape.",
      "src": "https://images.pexels.com/photos/8221363/pexels-photo-8221363.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/8221363/pexels-photo-8221363.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/8221363/pexels-photo-8221363.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/8221363/pexels-photo-8221363.jpeg",
      "src_tiny": "https://images.pexels.com/photos/8221363/pexels-photo-8221363.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 7952,
      "height": 5304
    },
    {
      "id": 8221203,
      "color": "#B07356",
      "url": "https://www.pexels.com/photo/a-woman-with-creative-make-up-lying-on-brown-ground-while-looking-at-the-camera-8221203/",
      "photographer": "Mikhail Nilov",
      "alt": "A striking portrait of a model with vibrant makeup and futuristic elements on rugged terrain.",
      "src": "https://images.pexels.com/photos/8221203/pexels-photo-8221203.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/8221203/pexels-photo-8221203.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/8221203/pexels-photo-8221203.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/8221203/pexels-photo-8221203.jpeg",
      "src_tiny": "https://images.pexels.com/photos/8221203/pexels-photo-8221203.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 7952,
      "height": 5304
    },
    {
      "id": 7778890,
      "color": "#797F86",
      "url": "https://www.pexels.com/photo/a-woman-posing-for-a-photoshoot-7778890/",
      "photographer": "Ron Lach",
      "alt": "Model posing in a stylish dress during a professional studio photoshoot.",
      "src": "https://images.pexels.com/photos/7778890/pexels-photo-7778890.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/7778890/pexels-photo-7778890.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/7778890/pexels-photo-7778890.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/7778890/pexels-photo-7778890.jpeg",
      "src_tiny": "https://images.pexels.com/photos/7778890/pexels-photo-7778890.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6171,
      "height": 4115
    },
    {
      "id": 7778897,
      "color": "#5D5F62",
      "url": "https://www.pexels.com/photo/a-model-posing-for-a-photoshoot-7778897/",
      "photographer": "Ron Lach",
      "alt": "A professional studio shoot featuring a model in a silver dress with a photographer and assistant.",
      "src": "https://images.pexels.com/photos/7778897/pexels-photo-7778897.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/7778897/pexels-photo-7778897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/7778897/pexels-photo-7778897.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/7778897/pexels-photo-7778897.jpeg",
      "src_tiny": "https://images.pexels.com/photos/7778897/pexels-photo-7778897.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6720,
      "height": 4480
    },
    {
      "id": 21792386,
      "color": "#8A8893",
      "url": "https://www.pexels.com/photo/model-in-blazer-and-short-21792386/",
      "photographer": "Petrovskii  Anton",
      "alt": "Elegant portrait of a fashionable woman with afro hairstyle in a studio setting.",
      "src": "https://images.pexels.com/photos/21792386/pexels-photo-21792386.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/21792386/pexels-photo-21792386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/21792386/pexels-photo-21792386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/21792386/pexels-photo-21792386.jpeg",
      "src_tiny": "https://images.pexels.com/photos/21792386/pexels-photo-21792386.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6589,
      "height": 4942
    },
    {
      "id": 17978994,
      "color": "#211C18",
      "url": "https://www.pexels.com/photo/blonde-woman-posing-in-the-dark-17978994/",
      "photographer": "Mason McCall",
      "alt": "Sophisticated studio shot of a blonde woman posing gracefully in dark attire, showcasing fashion and elegance.",
      "src": "https://images.pexels.com/photos/17978994/pexels-photo-17978994.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/17978994/pexels-photo-17978994.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/17978994/pexels-photo-17978994.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/17978994/pexels-photo-17978994.jpeg",
      "src_tiny": "https://images.pexels.com/photos/17978994/pexels-photo-17978994.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6622,
      "height": 4724
    }
  ],
  "craft": [
    {
      "id": 6461156,
      "color": "#886B55",
      "url": "https://www.pexels.com/photo/person-sewing-the-button-on-the-black-cloth-6461156/",
      "photographer": "Pavel Danilyuk",
      "alt": "Close-up of a tailor sewing a button with a needle and thread.",
      "src": "https://images.pexels.com/photos/6461156/pexels-photo-6461156.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/6461156/pexels-photo-6461156.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/6461156/pexels-photo-6461156.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/6461156/pexels-photo-6461156.jpeg",
      "src_tiny": "https://images.pexels.com/photos/6461156/pexels-photo-6461156.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6016,
      "height": 4016
    },
    {
      "id": 13206033,
      "color": "#8D5532",
      "url": "https://www.pexels.com/photo/person-using-a-sewing-machine-13206033/",
      "photographer": "Swastik Arora",
      "alt": "Handcrafting vibrant fabric decorations using a manual sewing machine in a lively workshop.",
      "src": "https://images.pexels.com/photos/13206033/pexels-photo-13206033.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/13206033/pexels-photo-13206033.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/13206033/pexels-photo-13206033.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/13206033/pexels-photo-13206033.jpeg",
      "src_tiny": "https://images.pexels.com/photos/13206033/pexels-photo-13206033.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6000,
      "height": 4000
    },
    {
      "id": 6757412,
      "color": "#8F8577",
      "url": "https://www.pexels.com/photo/close-up-of-a-sweater-fabric-6757412/",
      "photographer": "www.kaboompics.com",
      "alt": "Detailed close-up of beige cable knit wool texture, showcasing intricate woven patterns.",
      "src": "https://images.pexels.com/photos/6757412/pexels-photo-6757412.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/6757412/pexels-photo-6757412.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/6757412/pexels-photo-6757412.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/6757412/pexels-photo-6757412.jpeg",
      "src_tiny": "https://images.pexels.com/photos/6757412/pexels-photo-6757412.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 4480,
      "height": 6720
    }
  ],
  "journal": [
    {
      "title": "On Slow Cloth",
      "deck": "Why we still finish seams by hand at the Porto atelier \u2014 and what we learned weaving with the Henriques family.",
      "category": "Field Notes",
      "read": "6 min read",
      "img": "https://images.pexels.com/photos/20251644/pexels-photo-20251644.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "alt": "Stylish woman in brown coat holds a fashion magazine with gloved hands, showcasing elegance."
    },
    {
      "title": "The Weight of Wool",
      "deck": "A week with the spinners of Biella, where worsted yarn is still made on looms older than the studio that orders them.",
      "category": "Material",
      "read": "9 min read",
      "img": "https://images.pexels.com/photos/29512755/pexels-photo-29512755.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "alt": "Handmade slip-on shoes crafted from recycled materials, showcasing sustainable fashion in Uganda."
    },
    {
      "title": "Worn Eight Years",
      "deck": "Three of our customers on the Verre coat, mended twice, repaired once, and still in rotation through every winter.",
      "category": "Worn-In",
      "read": "4 min read",
      "img": "https://images.pexels.com/photos/6110230/pexels-photo-6110230.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "alt": "Two women pose stylishly on a convertible in a desert landscape, showcasing modern fashion."
    }
  ],
  "about": [
    {
      "id": 6665054,
      "color": "#B6A79B",
      "url": "https://www.pexels.com/photo/a-woman-in-white-and-blue-long-sleeve-shirt-touching-the-sleeve-of-a-person-6665054/",
      "photographer": "Antoni Shkraba Studio",
      "alt": "A fashion designer adjusts a model's outfit in a creative studio space filled with inspiration boards.",
      "src": "https://images.pexels.com/photos/6665054/pexels-photo-6665054.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/6665054/pexels-photo-6665054.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/6665054/pexels-photo-6665054.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/6665054/pexels-photo-6665054.jpeg",
      "src_tiny": "https://images.pexels.com/photos/6665054/pexels-photo-6665054.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 4000,
      "height": 6000
    },
    {
      "id": 9850083,
      "color": "#7D6D5E",
      "url": "https://www.pexels.com/photo/people-working-in-an-atelier-9850083/",
      "photographer": "Ron Lach",
      "alt": "Fashion designers working together in a modern atelier with sewing machines and patterns.",
      "src": "https://images.pexels.com/photos/9850083/pexels-photo-9850083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/9850083/pexels-photo-9850083.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/9850083/pexels-photo-9850083.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/9850083/pexels-photo-9850083.jpeg",
      "src_tiny": "https://images.pexels.com/photos/9850083/pexels-photo-9850083.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 6145,
      "height": 4097
    },
    {
      "id": 36050827,
      "color": "#B0A589",
      "url": "https://www.pexels.com/photo/close-up-of-beige-and-green-textured-fabric-36050827/",
      "photographer": "Moussa Idrissi",
      "alt": "Detailed view of beige and green patterned fabric with organic textures.",
      "src": "https://images.pexels.com/photos/36050827/pexels-photo-36050827.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
      "src_portrait": "https://images.pexels.com/photos/36050827/pexels-photo-36050827.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=1200&w=800",
      "src_landscape": "https://images.pexels.com/photos/36050827/pexels-photo-36050827.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "src_original": "https://images.pexels.com/photos/36050827/pexels-photo-36050827.jpeg",
      "src_tiny": "https://images.pexels.com/photos/36050827/pexels-photo-36050827.jpeg?auto=compress&cs=tinysrgb&dpr=1&fit=crop&h=200&w=280",
      "width": 7360,
      "height": 4912
    }
  ],
  "pexels_key": "Z6FQxyokT22L5aj35yzNeaPaA5MHPwxRd3HCKCwm6rpfnLZfHQj0lGRk"
};
